### PR TITLE
Add occupation to output

### PR DESCRIPTION
**Pull request by InTheFog-DT**
Main point of this PR is to add the occupation to the output. I changed the file output format to CSV for organizational purposes. The first and second row is the first name and combo of the middle name (if applicable) through last name respectively. The last column will contain the occupation.

### CODE REVIEW

**Comment by initstring** [comment]
Hi @InTheFog-DT ,

Thanks for the PR! I can definitely see how having a job title would be beneficial to some, but it looks like the CSV files that are produced are actually no longer useful as username wordlists without first processing a column out of the CSV. I think this ultimately makes the tool a bit harder to use, at least for the original intended functionality.

What about adding the job titles only to the rawnames.csv file?

**Comment by InTheFog-DT** [comment]
Hi @initstring -- True, this does add to the verbosity/complexity of the output. This is a format that I've found useful when integrating the linkedin2username output with phishing tools like GoPhish. Often you'll want to customize the e-mail with the first name of the employee. And the job title is nice to remove IT related personnel or to target a specific department.

No problem on my end adding to a separate file, though I'm going to keep it as is on my fork as this is the best format for me. Feel free to close the PR or edit as needed.

Cheers mate!

**Comment by initstring** [comment]
Thanks for explaining the use case - this makes perfect sense in that context. I'm going to leave this PR open for a bit, just need some time to think on it. Thanks again for the good contribution! Apologies if it takes me a bit to circle back on this one, just juggling a few things right now.

**Comment by InTheFog-DT** [comment]
No worries at all. Thanks for open sourcing a useful tool.

**Comment by initstring** [comment]
Wow, this has been a long time. Sorry about that!
I'm going to close this one without merging. It is a good idea, but it starts to creep into additional functionality. It's functionality that may be worth adding if I ever do a rewrite, and I will keep that in mind.
Thanks again.

**Pull request closed without merging**
