### PR TITLE
Update linkedin2username.py

### PR DESCRIPTION
**Pull request by pich4ya**
update the current version of linkedin mobile's title.

### CODE REVIEW

**Comment by initstring** [comment]
Hi, pich4ya!

Thank you so much for contributing to the project!

I just manually went through a logon process and reviewed the responses in Burp Suite. I still see `<title>LinkedIn</title>` being returned, and I am not having any issues using the tool as it is.

However, I have noticed in the past occasions where I needed to run the tool twice to get a logon.

How did you come across this issue? Can you verify that you are receiving your version of the title consistently? I can not reproduce this.

If LinkedIn is being inconsistent with the reply, I might need to find another string to match for at logon.

Any specific feedback you can give would be much appreciated.

Thanks!

burp

**Comment by initstring** [comment]
Haven't heard back, closing this as I cannot reproduce any issue.

Thanks!

**Comment by pich4ya** [comment]
Hi @initstring , here is the response I got. I believe it is because we access from different country / region. Mine is from Thailand/Asia.

User-Agent is   'Mozilla/5.0 (Linux; U; Android 2.2; en-us; Droid Build/FRG22D) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1' as described in source code.

`<!DOCTYPE html><html lang="en-US" class="artdeco android android"><head><meta http-equiv="X-UA-Compatible" content="IE=EDGE"><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Feed | LinkedIn</title><meta name="asset-url" id="artdeco/static/images/icons.svg" content="https://static-exp2.licdn.com/sc/h/2dp5i2r6zprgy2p4espovebm6"><meta name="treeID" content="hwh1GLWGHhUAFdtssSoAAA=="><meta name="pageKey" content="p_mwlite_feed_updates"><meta name="appName" content="lite-frontend"><meta name="trackingId" content="/9PcCbsmR5mnwiVf5OwSRw=="><meta name="scrollPos" content="0"><meta name="gdpr_notice_CSS" id="gdpr_notice_CSS" content="https://static-exp2.licdn.com/sc/h/3l22s0kyaw301mcrh6w3ui4k"><meta name="gdpr_notice_JS" id="gdpr_notice_JS" content="https://static-exp2.licdn.com/sc/h/de2biei39gxxpbg541t3ji2me"><script type="text/javascript" src="https://static-exp2.licdn.com/sc/h/elzed4n0xh6h62tr916e0t4as"></script><script type="text/javascript" src="https://static-exp2.licdn.com/sc/h/5tctnfjbd8qfcxatqqrk4kews"></script><script type="text/javascript" src="https://static-exp2.licdn.com/sc/h/4liy0m737lunktldc1acw330c"></script><script type="text/javascript" src="https://static-exp2.licdn.com/sc/h/9r19nh2bvvebtmz1ed1ghr9ow"></script><script type="text/javascript" src="https://static-exp2.licdn.com/sc/h/d2dfc9k162mkwr773wf81knoi"></script><link rel="stylesheet" href="https://static-exp2.licdn.com/sc/h/dnk42gqv1t3nzzoyiudgqi99y"/><link rel="manifest" href="/mwlite/manifest.json" crossOrigin='use-credentials'><meta name="push_notif_js_path" content="https://static-exp2.licdn.com/sc/h/87xymbetoxbsjedffy171jbhz"><meta name="pillar" content="feed"></head><body class="lite-default system-fonts body-nav-v2 "><nav class="nav_v2"><ol id="primary-nav"><li class="nav-item  active-nav"><a href="/mwlite/feed/" class="nav-link" id="nav-home" title=title><div class="icon-container"><li-icon class="icon"  active="true" type="nav-home-icon" ><svg viewBox="0 0 32 32" width="32px" height="32px" x="0" y="0" preserveAspectRatio="xMinYMin meet"class="nav-icon"><g class="active-item" style="fill-opacity: 1"><path d="M28,12.6L16.8,5.2c-0.5-0.3-1.1-0.3-1.6,0L4,12.6l1.1,1.6L7,13v12c0,0.6,0.4,1,1,1h6v-6h4v6h6c0.6,0,1-0.4,1-1V13l1.9,1.3L28,12.6z"></path></g><g class="inactive-item" style="fill: currentColor"><path d="M16,6.9l7,4.6V24h-4v-6h-6v6H9V11.5L16,6.9 M16,5c-0.3,0-0.6,0.1-0.8,0.2L4,12.6l1.1,1.6L7,13v12c0,0.6,0.4,1,1,1h7v-6h2v6h7c0.6,0,1-0.4,1-1V13l1.9,1.3l1.1-1.7L16.8,5.2C16.6,5.1,16.3,5,16,5L16,5z"></path></g></svg></li-icon><span id="home-badge" class="badge hidden medium-inverse"></span><div class="nav-icon-content">Home</div></div></a></li><li class="nav-item "><a href="/mwlite/jobs" class="nav-link" id="nav-jobs" title=title><div class="icon-container"><li-icon class="icon"  type="nav-jobs-icon" ><svg viewBox="0 0 32 32" width="32px" height="32px" x="0" y="0" preserveAspectRatio="xMinYMin meet"class="nav-icon"><g class="active-item" style="fill-opacity: 1"><path d="M4,16v9a1,1,0,0,0,1,1H27a1,1,0,0,0,1-1V16H4Z"></path><path d="M28,15V10a1,1,0,0,0-1-1H21V8a3,3,0,0,0-3-3H14a3,3,0,0,0-3,3V9H5a1,1,0,0,0-1,1v5H28ZM13,8a1,1,0,0,1,1-1h4a1,1,0,0,1,1,1V9H13V8Z"></path></g><g class="inactive-item" style="fill: currentColor"><path d="M27,9h-6V8c0-1.7-1.3-3-3-3h-4c-1.7,0-3,1.3-3,3v1H5c-0.6,0-1,0.4-1,1v15c0,0.6,0.4,1,1,1h22c0.6,0,1-0.4,1-1V10C28,9.4,27.6,9,27,9z M13,8c0-0.6,0.4-1,1-1h4c0.6,0,1,0.4,1,1v1h-6V8z M26,24H6v-8h20V24z M26,15H6v-4h20V15z"></path></g></svg></li-icon><div class="nav-icon-content">Jobs</div></div></a></li><li class="nav-item "><a href="/mwlite/mynetwork/" class="nav-link" id="nav-people" title=title><div class="icon-container"><li-icon class="icon"  type="nav-people-icon" ><svg viewBox="0 0 32 32" width="32px" height="32px" x="0" y="0" preserveAspectRatio="xMinYMin meet"class="nav-icon"><g class="active-item" style="fill-opacity: 1">
[...]`

capture-linkedin

**Comment by initstring** [comment]
Excellent, thank you for this!
Let me take a look at a better solution - probably I will monitor the incoming cookies being set, or look for something else to flag.
Can you confirm what country you are logging in from? I will use a VPN to test.
Probably within a few days I can get a good patch for this.
Thanks!

**Comment by initstring** [comment]
Hello,

I've modified the login match with a regex now to instead check for:
```
'<title>*?LinkedIn*?</title>'
```

I also added some additional login error checks to determine if something is unexpected and to open a ticket. Would you mind trying and seeing if this version works for you? 

Thank you!!!

**Comment by initstring** [comment]
Assuming fixed and closing. Thanks!

**Pull request closed without merging**
